#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

KANI_ARGS=(
  cargo
  kani
  --features
  stwo-backend
  --output-format
  terse
  --harness
  kani_phase12_claim_bindings_accept_canonical_single_step
  --harness
  kani_phase12_claim_bindings_reject_any_binding_mismatch
  --harness
  kani_phase12_state_progress_accepts_canonical_single_step
  --harness
  kani_phase12_state_progress_rejects_any_progress_mismatch
  --harness
  kani_phase14_claim_bindings_accept_canonical_single_step
  --harness
  kani_phase14_claim_bindings_reject_any_binding_mismatch
  --harness
  kani_phase14_state_progress_accepts_canonical_single_step
  --harness
  kani_phase14_state_progress_rejects_any_progress_mismatch
  --harness
  kani_phase24_relation_sequence_accepts_contiguous_members
  --harness
  kani_phase24_relation_sequence_rejects_zero_width_member
  --harness
  kani_phase24_relation_sequence_rejects_non_contiguous_steps
  --harness
  kani_phase24_relation_sequence_rejects_boundary_mismatch
  --harness
  kani_phase25_interval_counts_accept_checked_differences
  --harness
  kani_phase25_interval_counts_cover_positive_nonzero_lookup_delta_case
  --harness
  kani_phase25_interval_counts_reject_underflow
  --harness
  kani_phase25_interval_counts_reject_zero_width_interval
  --harness
  kani_phase25_interval_reconstruction_rejects_boundary_mismatch
  --harness
  kani_phase25_interval_reconstruction_covers_contiguous_pair
  --harness
  kani_phase26_fold_shape_accepts_contiguous_pair
  --harness
  kani_phase26_fold_shape_covers_nonzero_lookup_delta_fold
  --harness
  kani_phase26_fold_shape_rejects_boundary_mismatch
  --harness
  kani_phase26_fold_shape_rejects_insufficient_bounded_arity
  --harness
  kani_phase27_chain_shape_accepts_contiguous_pair
  --harness
  kani_phase27_chain_shape_covers_nonzero_lookup_delta_chain
  --harness
  kani_phase27_chain_shape_rejects_boundary_mismatch
  --harness
  kani_phase27_chain_shape_rejects_insufficient_bounded_arity
  --harness
  kani_phase28_aggregation_shape_accepts_contiguous_pair
  --harness
  kani_phase28_aggregation_shape_covers_nonzero_lookup_delta_aggregate
  --harness
  kani_phase28_aggregation_shape_rejects_boundary_mismatch
  --harness
  kani_phase28_aggregation_shape_rejects_insufficient_bounded_arity
  --harness
  kani_phase30_manifest_accepts_valid_single_step_surface
  --harness
  kani_phase30_manifest_accepts_contiguous_pair
  --harness
  kani_phase30_manifest_shape_rejects_chain_boundary_mismatch
  --harness
  kani_phase30_manifest_shape_rejects_step_index_drift
  --harness
  kani_phase30_manifest_counts_accept_valid_bounded_counts
  --harness
  kani_phase30_manifest_counts_reject_zero_envelopes
  --harness
  kani_phase30_manifest_counts_reject_mismatched_totals
  --harness
  kani_phase37_hash32_accepts_lowercase_hex_boundary
  --harness
  kani_phase37_hash32_rejects_non_lowercase_hex_examples
  --harness
  kani_phase37_hash32_requires_exact_length
  --harness
  kani_phase36_receipt_flags_accept_canonical_nonclaim_receipt
  --harness
  kani_phase36_receipt_flags_reject_any_claim_or_missing_source_check
  --harness
  kani_phase37_receipt_flags_accept_canonical_source_bound_receipt
  --harness
  kani_phase37_receipt_flags_reject_any_claim_or_missing_source_check
  --harness
  kani_phase33_public_input_ordering_accepts_canonical_order
  --harness
  kani_phase33_public_input_lane_payload_wires_canonical_fields
  --harness
  kani_phase33_public_input_ordering_rejects_any_lane_drift
  --harness
  kani_phase45_bridge_flags_accept_canonical_boundary_width_bridge
  --harness
  kani_phase45_bridge_flags_reject_any_claim_replay_or_missing_verification
  --harness
  kani_phase45_public_input_lane_metadata_accepts_canonical_examples
  --harness
  kani_phase45_public_input_lane_metadata_rejects_index_or_label_drift
  --harness
  kani_phase47_wrapper_flags_accept_canonical_receipt_only_candidate
  --harness
  kani_phase47_wrapper_flags_reject_any_replay_or_false_claim
  --harness
  kani_phase48_attempt_flags_accept_canonical_no_go
  --harness
  kani_phase48_attempt_flags_reject_any_replay_or_false_claim
)

"${KANI_ARGS[@]}"
