pub mod assembly;
pub mod compiler;
pub mod config;
pub mod error;
pub mod geometry;
pub mod instruction;
pub mod interpreter;
pub mod memory;
pub mod model;
pub mod runtime;
pub mod state;
pub mod tui;
pub mod verification;

pub use assembly::parse_program;
pub use compiler::ProgramCompiler;
pub use config::{Attention2DMode, TransformerVmConfig};
pub use error::{Result, VmError};
pub use geometry::{HullKvCache, Point2D};
pub use instruction::{Instruction, Program};
pub use interpreter::{NativeExecutionResult, NativeInterpreter, NativeTraceEntry};
pub use memory::AddressedMemory;
pub use model::{DispatchInfo, TransformerVm};
pub use runtime::{ExecutionResult, ExecutionRuntime, ExecutionTraceEntry};
pub use state::{decode_state, encode_state, MachineState, MIN_D_MODEL};
pub use tui::run_execution_tui;
pub use verification::{verify_model_against_native, ExecutionComparison};
